package ru.AndrewLevchenko;

/*Problem:

The sequence of triangle numbers is generated by adding the natural numbers. S
o the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Note: run as "java -cp ./..package folder../ru.AndrewLevchenko.problem_11"
*/

public class problem_12 {

	private static long Triangle_number(long k) {
		return (k * (k + 1) / 2);
	}

	public static void main(String[] args) {

		var prime_gen = new Prime_generator();

		long left_limit = 2 * 2 * 2 * 2 * 2 * 2 * 2 * 3 * 3 * 3 * 5 * 7 * 11 * 13L;

		for (long i = Math.round(Math.sqrt(2 * left_limit));; i++) {
			prime_gen.reboot();
			var triangle = Triangle_number(i);
			var tria = triangle;
			int multiplier = 1;
			int counter = 0;

			var the_prime = prime_gen.give_next();
			for (; tria > 1; the_prime = prime_gen.give_next()) {

				while (tria % the_prime == 0) {
					counter++;
					tria = tria / the_prime;
				}
				multiplier = multiplier * (counter + 1);
				counter = 0;
			}

			if (multiplier >= 500) {
				System.out.println(triangle + " is a winner with " + multiplier + " multipliers\n");
				break;
			}
			;

		}

	}

}
