package ru.AndrewLevchenko;

/*Problem:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Note: run as "java -cp ./..../ru.AndrewLevchenko.problem_2 1000"
*/



public class problem_2 {
	public static void main(String[] args) {
		
		int limit=Integer.parseInt(args[0]);
		int a=2;
		int b=8;
		int c;
		int sum=a+b;
		
		c=a+4*b;
		
		while (c<limit)
		{
			sum+=c;
			a=b;
			b=c;
			c=a+4*b;
		};
		
		
		System.out.printf("Sum of odd number less than "+ limit+ " is " + sum+"\n");
	}}
